name: CI/CD
on: [push, pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        continue-on-error: true
        with:
          root_file: "main.tex"
          glob_root_file: false
          args: -f -shell-escape -interaction=nonstopmode
          latexmk_use_xelatex: true
          #extra_fonts: ./fonts/*.ttf
          post_compile: "latexmk -c"
      - name: Upload LaTeX document to artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: PDF
          path: main.pdf
      - name: Serve LaTeX document
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          exclude_assets: .gitignore

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: LaTeX linter (chktex)
        uses: j2kun/chktex-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}